version: '3'

services:
  postgres:
    container_name: cqblog-postgres
    image: postgres:15
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: rails_cqblog_app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: rails_cqblog_app_development
    ports:
      - "5432:5432"
    networks:
      - cqblog-dev-network
  redis:
    container_name: cqblog-redis
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - ./tmp/redis:/data
    networks:
      - cqblog-dev-network
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - cqblog-dev-network
networks:
  cqblog-dev-network:
    driver: bridge